spring:
  application:
    name: SmsGatewayLLM
  datasource:
    url: jdbc:postgresql://91.146.28.240:5432/sms_gateway
    username: sms_user
    password: sms_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8041
app:
  values:
    api:
      giga-chat:
        base-url:
          auth: "https://ngw.devices.sberbank.ru:9443"
          chat: "https://gigachat.devices.sberbank.ru"
        chat-settings:
          scope: "GIGACHAT_API_PERS"
          max-tokens: 512
        auth-key: "OGYwZTY3YTctMjllNi00NGM5LTg3ZGYtZmFkZTljODE5YjYwOjE1MzFhZGFjLTRkYzUtNGYwYS05ZDI1LTZiOWUwMzlkYzYzNw=="
      sms-gateway:
        base-url: "https://api.sms-gate.app/3rdparty/v1"
        username: "QQMBCT"
        password: "b0ettnzk5mdvhg"
    bot:
      username: '@vhjgvbhbhvbot'
      token: "5931458847:AAEhaEA5CgUmEiGKTXFlrIg8JZo0SHdFPpU"
    vk:
      group-id: club198086876
      access-token: "vk1.a.ETEl5fytf3px5JsgAJsfAohj__2dh0Ha-zEvSve9mZr_L-kF42OBG9lfwSabZDXCiLPl3FD6dOrf0xAUXcGKUZC5vckPn1bRIa7OYcf3zc5hrt3mSWT0Hb5n4EOLIIdZeoqkg0kATENmZLyH93X3Ql4ieqxLxdrcvt540pjTw08IJFQ6UE_DV0T_TAJjGqO6rdM4LQVPQfi4989RLmJ8Yw"

